version: '3.1'

services:
  graphql:
    build: ./graphql
    restart: always
    ports:
      - 4000:4000
    environment:
      MONGODB_SERVER: mongo
      MONGODB_DB: ${ENV_MONGODB_DB}
      MONGODB_USER: ${ENV_MONGODB_USER}
      MONGODB_PASSWORD: ${ENV_MONGODB_PASSWORD}
      APP_SECRET: ${APP_SECRET}
      EXPIRE_TIME: 86400
      USE_GRAPHIQL: "true"
    depends_on:
      - mongo
    command: sh ./runGraphQL.sh

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ENV_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ENV_MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${ENV_MONGODB_DB}
      MONGO_INITDB_USER: ${ENV_MONGODB_USER}
      MONGO_INITDB_PWD: ${ENV_MONGODB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ENV_MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ENV_MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ENV_MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ENV_MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  publisher:
    build: ./publisher
    restart: always
    depends_on:
      - mongo
      - graphql
    command: sh ./runPublish.sh
    environment:
      NODE_OPTIONS: --max-old-space-size=4046
      UNIVERSAL_ROUTER_ADDRESS: ${ENV_UNIVERSAL_ROUTER_ADDRESS}
      RPC_WEBSOCKET_URL: ${ENV_RPC_WEBSOCKET_URL}
      L2_UNIVERSAL_ROUTER_ADDRESS: ${ENV_L2_UNIVERSAL_ROUTER_ADDRESS}
      L2_RPC_WEBSOCKET_URL: ${ENV_L2_RPC_WEBSOCKET_URL}
      GRAPHQL_URL: "http://graphql:4000/graphql"
      APP_SECRET: ${APP_SECRET}

  batcher:
    build: ./publisher
    depends_on:
      - mongo
      - graphql
    command: sh ./runBatch.sh
    environment:
      MONGODB_DB: ${ENV_MONGODB_DB}
      MONGODB_USER: ${ENV_MONGODB_USER}
      MONGODB_PASSWORD: ${ENV_MONGODB_PASSWORD}
      MONGODB_SERVER: mongo
      NODE_OPTIONS: --max-old-space-size=4046
      BLOCK_RANGE_SIZE: 1
      RETRIEVE_DAYS: 1
      WAIT_TIME: 1000
      L2_BLOCK_RANGE_SIZE: 7
      L2_RETRIEVE_DAYS: 1
      L2_WAIT_TIME: 1000
      UNIVERSAL_ROUTER_ADDRESS: ${ENV_UNIVERSAL_ROUTER_ADDRESS}
      RPC_WEBSOCKET_URL: ${ENV_RPC_WEBSOCKET_URL}
      L2_UNIVERSAL_ROUTER_ADDRESS: ${ENV_L2_UNIVERSAL_ROUTER_ADDRESS}
      L2_RPC_WEBSOCKET_URL: ${ENV_L2_RPC_WEBSOCKET_URL}

volumes:
  mongodb_data:
